title:              A Speculative Writer
email:              ravneet.baansal@outlook.com
description:        A space to dump and present speculations
author:             Ravneet Baansal
baseurl:            "/ravneet-blog"
url:                "https://baansalravneet.github.io"
favicon:            "/img/title-image.jpg"

# Social Profiles
twitter_username:
github_username:    baansalravneet
facebook_username:
instagram_username: rony_plays_guitar
linkedin_username:  ravneet-baansal-09b64111a

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-X5PR5HZ7JL # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
